name: CI/CD

on:
   workflow_dispatch: null

jobs:
    builds:
       runs-on: ubuntu-latest
       steps:
           - name: Checkout the repository
             uses: actions/checkout@v3
             
           - name: Installing nginx server
             run: |
              sudo apt-get update
              sudo apt-get install nginx
              sudo service nginx start
              
           - name: App code repository configuration
             run: |
              sudo apt-get update
              sudo apt-get install maven
              mvn --version
              git config --global user.email "sukruth700@gmail.com"
              git config --global user.name "Sukruth"
              git clone https://${{secrets.TOKEN}}@github.com/my-git-org-sukruth/repo-new-jira.git
              cd repo-new-jira
              mvn install
              mvn compile
              mvn test
              mvn package
              ls
              pwd
              cd ..
              sudo cp -r repo-new-jira/* /var/www/html/
              cd /var/www/html
              ls
              
           - name: Uploading the artifact
             uses: actions/upload-artifact@v3
             with:
               name: Package
               path: /home/runner/work/repo-new-jira/repo-new-jira/repo-new-jira/target
